steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mythic-beanbag-463309-e9/myapp:$SHORT_SHA', '.']

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mythic-beanbag-463309-e9/myapp:$SHORT_SHA']

  # Step 3: Replace placeholders in deployment YAML
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        sed -i "s|\$PROJECT_ID|mythic-beanbag-463309-e9|g" k8s/deployment.yaml
        sed -i "s|\$SHORT_SHA|$SHORT_SHA|g" k8s/deployment.yaml

  # Step 4: Deploy to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=vamsi-cluster'

images:
  - 'gcr.io/mythic-beanbag-463309-e9/myapp:$SHORT_SHA'
